apiVersion: v1
kind: Service
metadata:
  name: mern-client-service
spec:
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      port: 80 # The port exposed by your client container
      targetPort: 3000 # The port your client container is listening on
