apiVersion: v1
kind: Service
metadata:
  name: mern-server-service
spec:
  selector:
    app: mern-server
  ports:
    - protocol: TCP
      port: 80 # The port exposed by your server container
      targetPort: 8000 # The port your server container is listening on
